name: Test build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends flatpak-builder make
          flatpak remote-add --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: |
          # Only build a single version to speed up CI.
          echo 'DRIVER_VERSIONS="${BETA_VERSIONS%% *}"' >> versions.sh
          make
